# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LevelIOSSdkExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LevelIOSSdkExample
  pod 'iOSDFULibrary', '~> 2.0.1'

  target 'LevelIOSSdkExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LevelIOSSdkExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
